version: '3.4'
# https://www.yogihosting.com/docker-compose-aspnet-core/

services:
  patientfront: 
    environment:
      - ASPNETCORE_ENVIRONMENT=Development            
      #Dockerfile exposed port.   
      - ASPNETCORE_HTTPS_PORTS=443 
      #FIXRUN02- ASPNETCORE_HTTP_PORTS=80
    #ports:
    #  - "80" #http
    #  - "443" #https
    volumes:    
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro #https certificate password.
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro #https certificate file.    

  patientbackapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development            
      #Dockerfile exposed port.   
      - ASPNETCORE_HTTPS_PORTS=443 
      #FIXRUN02- ASPNETCORE_HTTP_PORTS=80
    #ports:
    #  - "80" #http
    #  - "443" #https 
    volumes:    
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro #https certificate password.
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro #https certificate file.    

  patientdiabeteriskbackapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development            
      #Dockerfile exposed port.   
      - ASPNETCORE_HTTPS_PORTS=443 
      #FIXRUN02 ASPNETCORE_HTTP_PORTS=80
    #ports:
    #  - "80" #http
    #  - "443" #https
    volumes:    
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro #https certificate password.
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro #https certificate file.    

  patientnotebackapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development            
      #Dockerfile exposed port.   
      - ASPNETCORE_HTTPS_PORTS=443 
      #FIXRUN02- ASPNETCORE_HTTP_PORTS=80
    #ports:
    #  - "80" #http
    #  - "443" #https
    volumes:    
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro #https certificate password.
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro #https certificate file.    

  ocelotapigateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development            
      #Dockerfile exposed port.   
      - ASPNETCORE_HTTPS_PORTS=443 
      #FIXRUN02- ASPNETCORE_HTTP_PORTS=80
    #ports:
    #  - "80" #http
    #  - "443" #https 
    volumes:    
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro #https certificate password.
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro #https certificate file.          